ESP_R, ESP_G, ESP_B = 255,255,255
HP_ESP_Status = False
ESP_Status = False
line = 0.6
Distance_ESP_Status = False
enit_distance = 780
Chams_R, Chams_G, Chams_B = 255,255,255
Chams_status = False
Night_Mod_Status = False
Night_Mod_value = 0.010
player_FOV = 90
AIM_Bot_Status = False
fov = 26
smooth = 10
AIM_Bot_bone = 8
AIM_Mouse_Status = False
RCS_Status = False
RCS_X, RCS_Y = 50,50
Trigger_BOT_Status = False
delay = 0.3
Skinchanger_Status = False
Auto_Pistol_status = False
Bunny_Hop_status = False
No_Flash_Status = False