from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QColorDialog

class Ui_Form(object):
    def setupUi(self, Form):
        cb_style = "QCheckBox {color: white;spacing: 5px;font: 63 12pt \"Mayberry Pro\";}QCheckBox::indicator {width: 13px;height: 13px;}QCheckBox::indicator:unchecked {background-color: rgb(40,40,45);border: 1px solid white;}QCheckBox::indicator:unchecked:hover {background-color: rgb(45,45,50);border: 1px solid white;}QCheckBox::indicator:checked {background-color: #0097e6;border: 1px solid white;}QCheckBox::indicator:checked:hover {background-color: #00a8ff;border: 1px solid white;}"
        but_style = "QPushButton{background-color: rgb(255,255,255);border: none;border-radius: 3px;}"
        slid_style = "QSlider::groove:horizontal {height: 8px;background: #0097e6;}QSlider::handle:horizontal {background: #1e3799;width: 15px;}"
        Form.setObjectName("Form")
        Form.resize(650, 330)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resourse/image/star.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(0.98)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 650, 320))
        self.label.setStyleSheet("background-color: rgb(20,20,30);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(5, 5, 46, 20))
        self.checkBox.setStyleSheet(cb_style)
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 5, 30, 20))
        self.pushButton.setStyleSheet(but_style)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(5, 35, 45, 20))
        self.label_3.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(170, 35, 31, 20))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(40,40,40);border: 1px solid white;color: white;font: 63 11pt \"Mayberry Pro\";padding-top: -1px;")
        self.lineEdit.setMaxLength(3)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(5, 60, 71, 20))
        self.checkBox_2.setStyleSheet(cb_style)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(5, 85, 110, 20))
        self.checkBox_3.setStyleSheet(cb_style)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalSlider = QtWidgets.QSlider(Form)
        self.horizontalSlider.setGeometry(QtCore.QRect(5, 110, 110, 20))
        self.horizontalSlider.setStyleSheet(slid_style)
        self.horizontalSlider.setMinimum(5)
        self.horizontalSlider.setMaximum(780)
        self.horizontalSlider.setProperty("value", 780)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(125, 111, 25, 16))
        self.label_4.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_4.setObjectName("label_4")
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(5, 135, 66, 20))
        self.checkBox_4.setStyleSheet(cb_style)
        self.checkBox_4.setObjectName("checkBox_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 134, 30, 20))
        self.pushButton_2.setStyleSheet(but_style)
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setGeometry(QtCore.QRect(5, 160, 106, 20))
        self.checkBox_5.setStyleSheet(cb_style)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setGeometry(QtCore.QRect(5, 185, 106, 20))
        self.checkBox_6.setStyleSheet(cb_style)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalSlider_2 = QtWidgets.QSlider(Form)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(5, 210, 110, 20))
        self.horizontalSlider_2.setStyleSheet(slid_style)
        self.horizontalSlider_2.setMinimum(10)
        self.horizontalSlider_2.setMaximum(1000)
        self.horizontalSlider_2.setProperty("value", 10)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(125, 211, 38, 16))
        self.label_5.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_5.setObjectName("label_5")
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setGeometry(QtCore.QRect(5, 235, 49, 20))
        self.checkBox_7.setStyleSheet(cb_style)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalSlider_3 = QtWidgets.QSlider(Form)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(5, 260, 110, 20))
        self.horizontalSlider_3.setStyleSheet(slid_style)
        self.horizontalSlider_3.setMinimum(10)
        self.horizontalSlider_3.setMaximum(170)
        self.horizontalSlider_3.setProperty("value", 90)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(125, 261, 27, 16))
        self.label_6.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox_8 = QtWidgets.QCheckBox(Form)
        self.checkBox_8.setGeometry(QtCore.QRect(5, 285, 89, 20))
        self.checkBox_8.setStyleSheet(cb_style)
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 5, 2, 300))
        self.label_2.setStyleSheet("background-color: rgb(70,70,75);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.checkBox_9 = QtWidgets.QCheckBox(Form)
        self.checkBox_9.setGeometry(QtCore.QRect(220, 5, 48, 20))
        self.checkBox_9.setStyleSheet(cb_style)
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Form)
        self.checkBox_10.setGeometry(QtCore.QRect(220, 30, 81, 20))
        self.checkBox_10.setStyleSheet(cb_style)
        self.checkBox_10.setObjectName("checkBox_10")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(340, 5, 85, 22))
        self.comboBox.setStyleSheet("QComboBox{font: 63 10pt \"Mayberry Pro\";border: none;background-color: rgb(30,30,30);color: white;font-weight: bold;border: 1px solid white;}QComboBox::drop-down{border: none;background-color: rgb(100,100,100);font-weight: bold;}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(220, 55, 29, 20))
        self.label_7.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_7.setObjectName("label_7")
        self.horizontalSlider_4 = QtWidgets.QSlider(Form)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(220, 75, 110, 20))
        self.horizontalSlider_4.setStyleSheet(slid_style)
        self.horizontalSlider_4.setMinimum(1)
        self.horizontalSlider_4.setMaximum(26)
        self.horizontalSlider_4.setProperty("value", 26)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(340, 76, 25, 16))
        self.label_8.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(220, 95, 61, 20))
        self.label_9.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_9.setObjectName("label_9")
        self.horizontalSlider_5 = QtWidgets.QSlider(Form)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(220, 115, 110, 20))
        self.horizontalSlider_5.setStyleSheet(slid_style)
        self.horizontalSlider_5.setMinimum(1)
        self.horizontalSlider_5.setMaximum(30)
        self.horizontalSlider_5.setProperty("value", 10)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(340, 116, 25, 16))
        self.label_10.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_10.setObjectName("label_10")
        self.checkBox_11 = QtWidgets.QCheckBox(Form)
        self.checkBox_11.setGeometry(QtCore.QRect(220, 140, 95, 20))
        self.checkBox_11.setStyleSheet(cb_style)
        self.checkBox_11.setObjectName("checkBox_11")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(220, 162, 9, 20))
        self.label_11.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_11.setObjectName("label_11")
        self.horizontalSlider_6 = QtWidgets.QSlider(Form)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(220, 180, 110, 20))
        self.horizontalSlider_6.setStyleSheet(slid_style)
        self.horizontalSlider_6.setMinimum(1)
        self.horizontalSlider_6.setMaximum(100)
        self.horizontalSlider_6.setProperty("value", 50)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(340, 182, 24, 16))
        self.label_12.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(220, 200, 9, 20))
        self.label_13.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_13.setObjectName("label_13")
        self.horizontalSlider_7 = QtWidgets.QSlider(Form)
        self.horizontalSlider_7.setGeometry(QtCore.QRect(220, 220, 110, 20))
        self.horizontalSlider_7.setStyleSheet(slid_style)
        self.horizontalSlider_7.setMinimum(1)
        self.horizontalSlider_7.setMaximum(100)
        self.horizontalSlider_7.setProperty("value", 50)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(340, 222, 24, 16))
        self.label_14.setStyleSheet("font: 63 10pt \"Mayberry Pro\";text-align: left;")
        self.label_14.setObjectName("label_14")
        self.checkBox_12 = QtWidgets.QCheckBox(Form)
        self.checkBox_12.setGeometry(QtCore.QRect(220, 245, 100, 20))
        self.checkBox_12.setStyleSheet(cb_style)
        self.checkBox_12.setObjectName("checkBox_12")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(220, 275, 39, 20))
        self.label_15.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_15.setObjectName("label_15")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 275, 31, 20))
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setStyleSheet("background-color: rgb(40,40,40);border: 1px solid white;color: white;font: 63 11pt \"Mayberry Pro\";padding-top: -1px;\n")
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(430, 5, 2, 300))
        self.label_16.setStyleSheet("background-color: rgb(70,70,75);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.checkBox_13 = QtWidgets.QCheckBox(Form)
        self.checkBox_13.setGeometry(QtCore.QRect(440, 5, 106, 20))
        self.checkBox_13.setStyleSheet(cb_style)
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_14 = QtWidgets.QCheckBox(Form)
        self.checkBox_14.setGeometry(QtCore.QRect(440, 30, 99, 20))
        self.checkBox_14.setStyleSheet(cb_style)
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(Form)
        self.checkBox_15.setGeometry(QtCore.QRect(440, 55, 97, 20))
        self.checkBox_15.setStyleSheet(cb_style)
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_16 = QtWidgets.QCheckBox(Form)
        self.checkBox_16.setGeometry(QtCore.QRect(440, 80, 98, 20))
        self.checkBox_16.setStyleSheet(cb_style)
        self.checkBox_16.setObjectName("checkBox_16")
        self.checkBox_17 = QtWidgets.QCheckBox(Form)
        self.checkBox_17.setGeometry(QtCore.QRect(440, 105, 80, 20))
        self.checkBox_17.setStyleSheet(cb_style)
        self.checkBox_17.setObjectName("checkBox_17")
        self.checkBox_18 = QtWidgets.QCheckBox(Form)
        self.checkBox_18.setGeometry(QtCore.QRect(440, 130, 111, 20))
        self.checkBox_18.setStyleSheet(cb_style)
        self.checkBox_18.setObjectName("checkBox_18")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(0, 310, 650, 20))
        self.label_17.setStyleSheet("background-color: rgb(55,55,60);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(5, 309, 640, 20))
        self.label_18.setStyleSheet("font: 63 12pt \"Mayberry Pro\";")
        self.label_18.setObjectName("label_18")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Maze V4"))
        self.checkBox.setText(_translate("Form", "ESP"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">length</span></p></body></html>"))
        self.lineEdit.setText(_translate("Form", "0.6"))
        self.checkBox_2.setText(_translate("Form", "HP ESP"))
        self.checkBox_3.setText(_translate("Form", "Distance ESP"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">780</span></p></body></html>"))
        self.checkBox_4.setText(_translate("Form", "Chams"))
        self.checkBox_5.setText(_translate("Form", "Light model"))
        self.checkBox_6.setText(_translate("Form", "Night mod"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.010</span></p></body></html>"))
        self.checkBox_7.setText(_translate("Form", "FOV"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">90</span></p></body></html>"))
        self.checkBox_8.setText(_translate("Form", "Game WH"))
        self.checkBox_9.setText(_translate("Form", "AIM"))
        self.checkBox_10.setText(_translate("Form", "Mouse 1"))
        self.comboBox.setItemText(0, _translate("Form", "Nearest"))
        self.comboBox.setItemText(1, _translate("Form", "Head"))
        self.comboBox.setItemText(2, _translate("Form", "Neck"))
        self.comboBox.setItemText(3, _translate("Form", "Chest"))
        self.comboBox.setItemText(4, _translate("Form", "Stomach"))
        self.comboBox.setItemText(5, _translate("Form", "Pelvis"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">FOV</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">26</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Smooth</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">10</span></p></body></html>"))
        self.checkBox_11.setText(_translate("Form", "RCS"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">X</span></p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">50</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Y</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">50</span></p></body></html>"))
        self.checkBox_12.setText(_translate("Form", "Trigger Bot"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">Delay</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("Form", "0.3"))
        self.checkBox_13.setText(_translate("Form", "Skinchanger"))
        self.checkBox_14.setText(_translate("Form", "Auto pistol"))
        self.checkBox_15.setText(_translate("Form", "Bunny hop"))
        self.checkBox_16.setText(_translate("Form", "Radar hack"))
        self.checkBox_17.setText(_translate("Form", "No flash"))
        self.checkBox_18.setText(_translate("Form", "Show money"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Maze V4</span></p></body></html>"))